template = """{{ country_code }} = utils.Item(value="{{ id }}")  # {{ country_name_on_russian }}"""

example = """
0	Россия	russia	aiva, any, beeline, center2m, danycom, ezmobile, lycamobile, matrix, megafon, motiv, mts, mtt, mtt_virtual, rostelecom, sber, simsim, tele2, tinkoff, ttk, winmobile, yota,
1	Украина	ukraine	3mob, any, intertelecom, kyivstar, life, lycamobile, mts, utel, vodafone,
2	Казахстан	kazakhstan	activ, altel, any, beeline, kcell, tele2,
3	Китай	china	any, chinamobile, china_unicom, unicom,
4	Филиппины	philippines	any, globe_telecom, smart, tm,
5	Мьянма	myanmar	any, telenor,
6	Индонезия	indonesia	any, axis, indosat, telkomsel, three,
7	Малайзия	malaysia	any, celcom, digi, hotlink, u_mobile,
8	Кения	kenya	airtel, any, econet, orange, safaricom, telkom,
9	Танзания	tanzania	any,
10	Вьетнам	vietnam	any, itelecom, mobifone, vietnamobile, viettel, vinaphone,
11	Кыргызстан	kyrgyzstan	any, beeline, megacom, o!,
12	США (виртуальные)	usa	any, cellular, tmobile,
13	Израиль	israel	019mobile, any, golan_telecom, home_cellular, hot_mobile, jawwal, ooredoo, orange, pelephone, rami_levy,
14	Гонконг	hongkong	any, chinamobile, csl_mobile, imc, three, unicom,
15	Польша	poland	aero2, any, e_telko, klucz, lycamobile, netia, orange, play, plus, tmobile,
16	Англия	england	any, cmlink, ee, ezmobile, lebara, lycamobile, o2, talk_telecom, three, tmobile, vectone, vodafone,
18	Дем.Конго	dcongo	africel, airtel, any, orange, vodacom,
19	Нигерия	nigeria	airtel, any, etisalat, glomobile, mtn,
21	Египет	egypt	any, etisalat, orange, vodafone,
22	Индия	india	any,
23	Ирландия	ireland	any, lycamobile,
24	Камбоджа	cambodia	any,
25	Лаос	laos	any, etl, telekom, tplus, unitel,
26	Гаити	haiti	any, natcom,
27	Кот д'Ивуар	ivory	any, moov, mtn, orange,
28	Гамбия	gambia	africel, any, comium, gamcel, qcell,
29	Сербия	serbia	any, mobtel, mts, vip,
30	Йемен	yemen	any, mtn, sabafon, yemen_mobile,
31	Южная Африка	southafrica	any, vodacom,
32	Румыния	romania	any, digi, lycamobile, my_avon, orange, runex_telecom, telekom, vodafone,
33	Колумбия	colombia	any, claro,
34	Эстония	estonia	any, elisa, goodline, super, tele2, topconnect,
36	Канада	canada	any, cellular, lucky,
37	Марокко	morocco	any, inwi, itissalat, orange,
38	Гана	ghana	airtel, any, glomobile, millicom, mtn, vodafone,
39	Аргентина	argentina	any,
40	Узбекистан	uzbekistan	any, beeline, mts, ucell, uzmobile,
41	Камерун	cameroon	any, mtn, nexttel, orange,
42	Чад	chad	airtel, any, salam, tigo,
43	Германия	germany	any, fonic, lebara, lycamobile, o2, ortel_mobile, telekom, vodafone,
44	Литва	lithuania	any, tele2, telia,
45	Хорватия	croatia	a1, any, tele2, tmobile,
46	Швеция	sweden	any, comviq, lycamobile, tele2, telenor, telia, three, vectone, vodafone,
47	Ирак	iraq	any, asiacell, korek, zain,
48	Нидерланды	netherlands	any, kpn, lebara, lycamobile, l_mobi, tmobile, vodafone,
49	Латвия	latvia	any, tele2,
50	Австрия	austria	a1, any, orange, telering, three, tmobile,
51	Беларусь	belarus	any, life, mdc, mts,
52	Таиланд	thailand	ais, any, dtac, truemove,
53	Сауд. Аравия	saudiarabia	any,
54	Мексика	mexico	any, telcel,
55	Тайвань	taiwan	any, chunghwa, fareast,
56	Испания	spain	any, lebara, lycamobile, orange, you_mobile,
57	Иран	iran	any, aptel, azartel, hamrah_e_aval, irancell, rightel, samantel, shatel, taliya,
58	Алжир	algeria	any, djezzy, mobilis, ooredoo,
60	Бангладеш	bangladesh	any,
61	Сенегал	senegal	any,
62	Турция	turkey	any, turkcell,
63	Чехия	czech	any, o2, tmobile, vodafone,
64	Шри-Ланка	srilanka	any,
65	Перу	peru	any,
66	Пакистан	pakistan	any,
67	Новая Зеландия	newzealand	2degree, any, vodafone,
68	Гвинея	guinea	any, cellcom, mtn, orange,
69	Мали	mali	any, malitel, orange, telecel,
70	Венесуэла	venezuela	any,
72	Монголия	mongolia	any, beeline,
73	Бразилия	brazil	algartelecom, any, claro, correios_celular, oi, tim, vivo,
74	Афганистан	afghanistan	any, salaam,
75	Уганда	uganda	airtel, any, k2_telecom, lycamobile, mtn, orange, smart, smile, uganda_telecom,
76	Ангола	angola	any,
77	Кипр	cyprus	any, cyta, epic, lemontel, primetel, vectone,
78	Франция	france	any, lebara, lycamobile, orange, sfr, syma_mobile, vectone,
79	Папуа-Новая Гвинея	papua	any,
80	Мозамбик	mozambique	any,
81	Непал	nepal	any,
85	Молдова	moldova	any, moldcell, orange, unite,
87	Парагвай	paraguay	any,
88	Гондурас	honduras	any,
89	Тунис	tunisia	any,
90	Никарагуа	nicaragua	any,
92	Боливия	bolivia	any,
94	Гватемала	guatemala	any,
95	ОАЭ	uae	any,
96	Зимбабве	zimbabwe	any,
98	Судан	sudan	any, mtn, zain,
101	Сальвадор	salvador	any,
102	Ливия	libyan	any,
103	Ямайка	jamaica	any, digi,
104	Тринидад и Тобаго	trinidad	any,
105	Эквадор	ecuador	any,
109	Доминиканская Республика	dominican	altice, any, claro,
114	Мавритания	mauritania	any, chinguitel, mattel, mauritel,
115	Сьерра-Леоне	sierraleone	africel, airtel, any,
116	Иордания	jordan	any, orange, umniah, xpress, zain,
117	Португалия	portugal	any, lycamobile, vodafone,
120	Бенин	benin	any,
121	Бруней	brunei	any,
123	Ботсвана	botswana	any, be_mobile, mascom, orange,
126	Доминика	dominica	any,
128	Грузия	georgia	any, geocell, hamrah_e_aval, magticom,
129	Греция	greece	any, cosmote, q_telecom, vodafone,
131	Гайана	guyana	any,
135	Либерия	liberia	any, cellcom, comium, libercell, libtelco, lonestar,
142	Суринам	suriname	any,
143	Таджикистан	tajikistan	any,
146	Реюньон	reunion	any,
148	Армения	armenia	any,
150	Конго	congo	any,
152	Буркина-Фасо	burkinafaso	airtel, any, onatel, telecel,
153	Ливан	lebanon	alfa, any, ogero, touch,
154	Габон	gabon	any,
157	Маврикий	mauritius	any,
158	Бутан	bhutan	any,
159	Мальдивы	maldives	any,
161	Туркменистан	turkmenistan	any,
172	Дания	denmark	any, lycamobile,
179	Аруба	aruba	any,
182	Япония	japan	any,
187	США	usaphysical	any, lycamobile, tmobile,
189	Фиджи	fiji	any,
190	Южная Корея	southkorea	any,
195	Бермуды	bermuda	any,
""".lstrip().rstrip()

code = """
from . import utils


class Country(utils.Helper):
"""


for split_line in example.split("\n"):
    country_id: int = int(split_line.split("	")[0])
    country_code: str = split_line.split("	")[2]
    country_name_on_russian: str = split_line.split("	")[1]

    rendered_template = template.replace(
        "{{ country_code }}", country_code.upper()
    ).replace(
        "{{ country_name_on_russian }}", country_name_on_russian
    ).replace(
        "{{ id }}", str(country_id)
    )

    code += "    {}\n".format(rendered_template)

print(code.lstrip().rstrip())