from . import utils


class Service(utils.Helper):
    VKONTAKTE = utils.Item(value="vk")  # Вконтакте
    ODNOKLASSNIKI = utils.Item(value="ok")  # Ok.ru
    ZDRAV_CITY = utils.Item(value="io")  # ЗдравСити
    QIWI = utils.Item(value="qw")  # Киви
    ULA = utils.Item(value="ym")  # Юла
    DGURVOKRUG = utils.Item(value="we")  # ДругВокруг
    PYTORACHKA = utils.Item(value="bd")  # Пятерочка
    YANDEX = utils.Item(value="ya")  # Яндекс
    PEKEKROSTOK = utils.Item(value="pl")  # Перекресток
    MAGNIT = utils.Item(value="mg")  # Магнит
    SPORTMASTER = utils.Item(value="yk")  # СпортМастер
    TIKTOK_DOUYIN = utils.Item(value="lf")  # TikTok/Douyin
    PCA = utils.Item(value="cy")  # РСА
    CASINO888 = utils.Item(value="ll")  # 888casino
    MVIDEO = utils.Item(value="tk")  # МВидео
    APP99 = utils.Item(value="ki")  # 99app
    SIKAYET_VAR = utils.Item(value="fs")  # Şikayet var
    KVARTPLATA_PLUS = utils.Item(value="yb")  # Квартплата+
    PREYMERIS_2020 = utils.Item(value="qc")  # Праймериз 2020
    VITA_EXPRESS = utils.Item(value="bj")  # Вита экспресс
    ONEXBET = utils.Item(value="wj")  # 1хbet
    SAMOKAT = utils.Item(value="jr")  # Самокат
    VERNYI = utils.Item(value="nb")  # Верный
    _1_6_8_8_RU = utils.Item(value="hn")  # 1688
    BANKI = utils.Item(value="md")  # Банки
    DETSKIY_MIR = utils.Item(value="rj")  # Детский мир
    STOLOTO = utils.Item(value="hj")  # Столото
    VKUSVILL = utils.Item(value="sh")  # ВкусВилл
    ELDORADPO = utils.Item(value="ke")  # Эльдорадо
    SBERMARKET = utils.Item(value="xj")  # СберМаркет
    SBERAPTEKA = utils.Item(value="sl")  # СберАптека
    RED23 = utils.Item(value="qi")  # 23red
    COM163 = utils.Item(value="wp")  # 163СOM
    CHAMPIONCASINO = utils.Item(value="uj")  # СhampionСasino
    FOUR_FUN = utils.Item(value="hk")  # 4Fun
    OKOLO = utils.Item(value="yz")  # Около
    BOOKMAKERS = utils.Item(value="ft")  # Букмекерские
    ANY = utils.Item(value="ot")  # Любой другой

    WHATSAPP = utils.Item(value="wa")  # Whatsapp
    VIBER = utils.Item(value="vi")  # Viber
    TELEGRAM = utils.Item(value="tg")  # Telegram
    WECHAT = utils.Item(value="wb")  # WeChat
    GOOGLE_YOUTUBE_GMAIL = utils.Item(value="go")  # Google,youtube,Gmail
    AVITO = utils.Item(value="av")  # avito
    FACEBOOK = utils.Item(value="fb")  # facebook
    TWITTER = utils.Item(value="tw")  # Twitter
    UBER = utils.Item(value="ub")  # Uber
    GETT = utils.Item(value="gt")  # Gett
    OLX = utils.Item(value="sn")  # OLX
    INSTAGRAM = utils.Item(value="ig")  # Instagram
    HEZZL = utils.Item(value="ss")  # Hezzl
    MAIL_RU = utils.Item(value="ma")  # Mail.ru
    MICROSOFT = utils.Item(value="mm")  # Microsoft
    AIRBNB = utils.Item(value="uk")  # Airbnb
    LINE_MSG = utils.Item(value="me")  # Line msg
    YAHOO = utils.Item(value="mb")  # Yahoo
    HQ_TRIVIA = utils.Item(value="kp")  # HQ Trivia
    DELIVERY_CLUB = utils.Item(value="dt")  # Delivery Club
    STEAM = utils.Item(value="mt")  # Steam
    TINDER = utils.Item(value="oi")  # Tinder
    MAMBA = utils.Item(value="fd")  # Mamba
    DENT = utils.Item(value="zz")  # Dent
    KAKAOTALK = utils.Item(value="kt")  # KakaoTalk
    AOL = utils.Item(value="pm")  # AOL
    LINKEDIN = utils.Item(value="tn")  # LinkedIN
    TENCENT_QQ = utils.Item(value="qq")  # Tencent QQ
    POF_COM = utils.Item(value="pf")  # pof.com
    YALLA = utils.Item(value="yl")  # Yalla
    KOLESA_KZ = utils.Item(value="kl")  # kolesa.kz
    PREMIUM_ONE = utils.Item(value="po")  # premium.one
    NAVER = utils.Item(value="nv")  # Naver
    NETFLIX = utils.Item(value="nf")  # Netflix
    ICQ = utils.Item(value="iq")  # icq
    ONLINERBY = utils.Item(value="ob")  # Onlinerby
    KUFARBY = utils.Item(value="kb")  # kufarby
    IMO = utils.Item(value="im")  # Imo
    MICHAT = utils.Item(value="mc")  # Michat
    DISCORD = utils.Item(value="ds")  # Discord
    SEOSPRINT = utils.Item(value="vv")  # Seosprint
    MONOBANK = utils.Item(value="ji")  # Monobank
    UKRNET = utils.Item(value="hu")  # Ukrnet
    SKOUT = utils.Item(value="wg")  # Skout
    EASYPAY = utils.Item(value="rz")  # EasyPay
    Q12_TRIVIA = utils.Item(value="vf")  # Q12 Trivia
    PYRO_MUSIC = utils.Item(value="ny")  # Pyro Music
    WOLT = utils.Item(value="rr")  # Wolt
    CLIQQ = utils.Item(value="fe")  # CliQQ
    SSOIDNET = utils.Item(value="la")  # ssoidnet
    ZOHO = utils.Item(value="zh")  # Zoho
    TICKETMASTER = utils.Item(value="gp")  # Ticketmaster
    AMAZON = utils.Item(value="am")  # Amazon
    OLACABS = utils.Item(value="ly")  # Olacabs
    RAMBLER = utils.Item(value="tc")  # Rambler
    PROTONMAIL = utils.Item(value="dp")  # ProtonMail
    NRJ_MUSIC_AWARDS = utils.Item(value="pg")  # NRJ Music Awards
    CITYMOBIL = utils.Item(value="yf")  # Citymobil
    MIRATORG = utils.Item(value="op")  # MIRATORG
    PGBONUS = utils.Item(value="fx")  # PGbonus
    MEGA = utils.Item(value="qr")  # MEGA
    CAREEM = utils.Item(value="ls")  # Careem
    BIGO_LIVE = utils.Item(value="bl")  # BIGO LIVE
    MYMUSICTASTE = utils.Item(value="mu")  # MyMusicTaste
    SNAPCHAT = utils.Item(value="fu")  # Snapchat
    KEYBASE = utils.Item(value="bf")  # Keybase
    OZON = utils.Item(value="sg")  # OZON
    WILDBERRIES = utils.Item(value="uu")  # Wildberries
    BLABLACAR = utils.Item(value="ua")  # BlaBlaCar
    ALIBABA = utils.Item(value="ab")  # Alibaba
    INBOXLV = utils.Item(value="iv")  # Inboxlv
    NTTGAME = utils.Item(value="zy")  # Nttgame
    SURVEYTIME = utils.Item(value="gd")  # Surveytime
    MYLOVE = utils.Item(value="fy")  # Mylove
    MOSRU = utils.Item(value="ce")  # mosru
    TRUECALLER = utils.Item(value="tl")  # Truecaller
    GLOBUS = utils.Item(value="hm")  # Globus
    BOLT = utils.Item(value="tx")  # Bolt
    SHOPEE = utils.Item(value="ka")  # Shopee
    BURGER_KING = utils.Item(value="ip")  # Burger King
    PROM = utils.Item(value="cm")  # Prom
    ALIPAY = utils.Item(value="hw")  # AliPay
    KARUSEL = utils.Item(value="de")  # Karusel
    IVI = utils.Item(value="jc")  # IVI
    INDRIVER = utils.Item(value="rl")  # inDriver
    HAPPN = utils.Item(value="df")  # Happn
    RUTUBE = utils.Item(value="ui")  # RuTube
    MAGNOLIA = utils.Item(value="up")  # Magnolia
    FOODPANDA = utils.Item(value="nz")  # Foodpanda
    WEIBO = utils.Item(value="kf")  # Weibo
    BILLMILL = utils.Item(value="ri")  # BillMill
    QUIPP = utils.Item(value="cc")  # Quipp
    OKTA = utils.Item(value="lr")  # Okta
    JDCOM = utils.Item(value="za")  # JDcom
    MTS_CASHBACK = utils.Item(value="da")  # MTS CashBack
    FIQSY = utils.Item(value="ug")  # Fiqsy
    KUCOINPLAY = utils.Item(value="sq")  # KuCoinPlay
    PAPARA = utils.Item(value="zr")  # Papara
    WISH = utils.Item(value="xv")  # Wish
    ICRYPEX = utils.Item(value="cx")  # Icrypex
    PADDYPOWER = utils.Item(value="cw")  # PaddyPower
    BAIDU = utils.Item(value="li")  # Baidu
    DOMINOS_PIZZA = utils.Item(value="dz")  # Dominos Pizza
    PAYCELL = utils.Item(value="xz")  # paycell
    LENTA = utils.Item(value="rd")  # Lenta
    PAYBERRY = utils.Item(value="qb")  # Payberry
    DROM = utils.Item(value="hz")  # Drom
    GLOBALTEL = utils.Item(value="gl")  # GlobalTel
    DELIVEROO = utils.Item(value="zk")  # Deliveroo
    SOCIOS = utils.Item(value="ia")  # Socios
    WMARACI = utils.Item(value="xl")  # Wmaraci
    YEMEKSEPETI = utils.Item(value="yi")  # Yemeksepeti
    NIKE = utils.Item(value="ew")  # Nike
    MYGLO = utils.Item(value="ae")  # myGLO
    YOUSTAR = utils.Item(value="gb")  # YouStar
    ROSAKHUTOR = utils.Item(value="qm")  # RosaKhutor
    EBAY = utils.Item(value="dh")  # eBay
    GG = utils.Item(value="qe")  # GG
    GRINDR = utils.Item(value="yw")  # Grindr
    OFFGAMERS = utils.Item(value="uz")  # OffGamers
    HEPSIBURADACOM = utils.Item(value="gx")  # Hepsiburadacom
    COINBASE = utils.Item(value="re")  # Coinbase
    DBRUA = utils.Item(value="tj")  # dbrUA
    PAYPAL = utils.Item(value="ts")  # PayPal
    HILY = utils.Item(value="rt")  # hily
    SNEAKERSNSTUFF = utils.Item(value="sf")  # SneakersnStuff
    DOSTAVISTA = utils.Item(value="sv")  # Dostavista
    BLIZZARD = utils.Item(value="bz")  # Blizzard
    EZBUY = utils.Item(value="db")  # ezbuy
    COINFIELD = utils.Item(value="vw")  # CoinField
    AIRTEL = utils.Item(value="zl")  # Airtel
    YANDEXGO = utils.Item(value="wf")  # YandexGo
    MRGREEN = utils.Item(value="lw")  # MrGreen
    REDIFFMAIL = utils.Item(value="co")  # Rediffmail
    MILOAN = utils.Item(value="ey")  # miloan
    PAYTM = utils.Item(value="ge")  # Paytm
    DHANI = utils.Item(value="os")  # Dhani
    CMTCUZDAN = utils.Item(value="ql")  # CMTcuzdan
    MERCADO = utils.Item(value="cq")  # Mercado
    DIDI = utils.Item(value="xk")  # DiDi
    MONESE = utils.Item(value="py")  # Monese
    KOTAK811 = utils.Item(value="rv")  # Kotak811
    HOPI = utils.Item(value="jl")  # Hopi
    TRENDYOL = utils.Item(value="pr")  # Trendyol
    JUSTDATING = utils.Item(value="pu")  # Justdating
    PAIRS = utils.Item(value="dk")  # Pairs
    TOUCHANCE = utils.Item(value="fm")  # Touchance
    SNAPPFOOD = utils.Item(value="ph")  # SnappFood
    NCSOFT = utils.Item(value="sw")  # NCsoft
    TOSLA = utils.Item(value="nr")  # Tosla
    ININAL = utils.Item(value="hy")  # Ininal
    PAYSEND = utils.Item(value="tr")  # Paysend
    CDKEYS = utils.Item(value="pq")  # CDkeys
    AVON = utils.Item(value="ff")  # AVON
    DODOPIZZA = utils.Item(value="sd")  # dodopizza
    MCDONALDS = utils.Item(value="ry")  # McDonalds
    E_BIKE_GEWINNSPIEL = utils.Item(value="le")  # E bike Gewinnspiel
    JKF = utils.Item(value="hr")  # JKF
    MYFISHKA = utils.Item(value="qa")  # MyFishka
    CRAIGSLIST = utils.Item(value="wc")  # Craigslist
    FOODY = utils.Item(value="kw")  # Foody
    GRAB = utils.Item(value="jg")  # Grab
    ZALO = utils.Item(value="mj")  # Zalo
    LIVESCORE = utils.Item(value="eu")  # LiveScore
    GAMER = utils.Item(value="ed")  # Gamer
    HUYA = utils.Item(value="pp")  # Huya
    WESTSTEIN = utils.Item(value="th")  # WestStein
    TANGO = utils.Item(value="xr")  # Tango
    GLOBAL24 = utils.Item(value="iz")  # Global24
    SHEERID = utils.Item(value="rx")  # Sheerid
    CAIXA = utils.Item(value="my")  # CAIXA
    OFFERUP = utils.Item(value="zm")  # OfferUp
    SWVL = utils.Item(value="tq")  # Swvl
    HARAJ = utils.Item(value="au")  # Haraj
    TAKSHEEL = utils.Item(value="ei")  # Taksheel
    HAMRAHAVAL = utils.Item(value="rp")  # hamrahaval
    GAMEKIT = utils.Item(value="pa")  # Gamekit
    GETIR = utils.Item(value="ul")  # Getir
    IRANCELL = utils.Item(value="cf")  # irancell
    ALFA = utils.Item(value="bt")  # Alfa
    DISNEY_HOTSTAR = utils.Item(value="ud")  # Disney Hotstar
    AGROINFORM = utils.Item(value="qu")  # Agroinform
    HUMBLEBUNDLE = utils.Item(value="un")  # humblebundle
    FABERLIC = utils.Item(value="rm")  # Faberlic
    CAFEBAZAAR = utils.Item(value="uo")  # CafeBazaar
    CRYPTOCOM = utils.Item(value="ti")  # cryptocom
    GITTIGIDIYOR = utils.Item(value="nk")  # Gittigidiyor
    MZADQATAR = utils.Item(value="jm")  # mzadqatar
    ALGIDA = utils.Item(value="lp")  # Algida
    CITA_PREVIA = utils.Item(value="si")  # Cita Previa
    POTATO_CHAT = utils.Item(value="fj")  # Potato Chat
    BITAQATY = utils.Item(value="pt")  # Bitaqaty
    AMASIA = utils.Item(value="yo")  # Amasia
    DREAM11 = utils.Item(value="ve")  # Dream11
    ORIFLAME = utils.Item(value="qh")  # Oriflame
    BYKEA = utils.Item(value="iu")  # Bykea
    IMMOWELT = utils.Item(value="ib")  # Immowelt
    DIGIKALA = utils.Item(value="zv")  # Digikala
    WING_MONEY = utils.Item(value="jb")  # Wing Money
    YAAY = utils.Item(value="vn")  # Yaay
    GAMEARENA = utils.Item(value="wn")  # GameArena
    AUCHAN = utils.Item(value="st")  # Auchan
    PICPAY = utils.Item(value="ev")  # Picpay
    BLUED = utils.Item(value="qn")  # Blued
    SPOTHIT = utils.Item(value="cd")  # SpotHit
    BRAND20UA = utils.Item(value="vo")  # Brand20ua
    IQOS = utils.Item(value="il")  # IQOS
    POWERKREDITE = utils.Item(value="dx")  # Powerkredite
    BISU = utils.Item(value="el")  # Bisu
    PAXFUL = utils.Item(value="dn")  # Paxful
    PUREPLATFROM = utils.Item(value="lk")  # PurePlatfrom
    BANQI = utils.Item(value="vc")  # Banqi
    MOBILE01 = utils.Item(value="wk")  # Mobile01
    AITU = utils.Item(value="jj")  # Aitu
    ADIDAS = utils.Item(value="an")  # Adidas
    HUMTA = utils.Item(value="gv")  # Humta
    DIVAR = utils.Item(value="dw")  # Divar
    CAROUSELL = utils.Item(value="gj")  # Carousell
    MOMO = utils.Item(value="hc")  # MOMO
    ENEBA = utils.Item(value="uf")  # Eneba
    VERSE = utils.Item(value="kn")  # Verse
    TAOBAO = utils.Item(value="qd")  # Taobao
    ONTAXI = utils.Item(value="zf")  # OnTaxi
    HOTLINE = utils.Item(value="gi")  # Hotline
    TATNEFT = utils.Item(value="uc")  # Tatneft
    RRSA = utils.Item(value="mn")  # RRSA
    DOUYU = utils.Item(value="ak")  # Douyu
    UKLON = utils.Item(value="cp")  # Uklon
    MONEYLION = utils.Item(value="qo")  # Moneylion
    APPLE = utils.Item(value="wx")  # Apple
    CLUBHOUSE = utils.Item(value="et")  # Clubhouse
    NIFTY = utils.Item(value="px")  # Nifty
    PINGPONG = utils.Item(value="jh")  # PingPong
    MAILRU_GROUP = utils.Item(value="lb")  # Mailru Group
    BITCLOUT = utils.Item(value="lt")  # BitClout
    SKROUTZ = utils.Item(value="sk")  # Skroutz
    MAPLESEA = utils.Item(value="oh")  # MapleSEA
    ROZETKA = utils.Item(value="km")  # Rozetka
    GALAXYWIN = utils.Item(value="af")  # GalaxyWin
    ZIGLU = utils.Item(value="tt")  # Ziglu
    LIKEE = utils.Item(value="jf")  # Likee
    CITYBASE = utils.Item(value="az")  # CityBase
    ALLEGRO = utils.Item(value="yn")  # Allegro
    YOUGOTAGIFT = utils.Item(value="wl")  # YouGotaGift
    LAZADA = utils.Item(value="dl")  # Lazada
    TRADINGVIEW = utils.Item(value="gc")  # TradingView
    FIVERR = utils.Item(value="cn")  # Fiverr
    GABI = utils.Item(value="ou")  # Gabi
    KWAI = utils.Item(value="vp")  # Kwai
    YUBO = utils.Item(value="uh")  # Yubo
    IQIYI = utils.Item(value="es")  # iQIYI
    GOODS = utils.Item(value="be")  # goods
    GLOVO = utils.Item(value="aq")  # Glovo
    IFOOD = utils.Item(value="pd")  # IFood
    QUACK = utils.Item(value="zw")  # Quack
    MOCOSPACE = utils.Item(value="gm")  # Mocospace
    DUNDLE = utils.Item(value="fi")  # Dundle
    SWITIPS = utils.Item(value="hg")  # Switips
    FACEIT = utils.Item(value="qz")  # Faceit
    LYKA = utils.Item(value="gz")  # LYKA
    PAYSAFECARD = utils.Item(value="jq")  # Paysafecard
    ONET = utils.Item(value="ue")  # Onet
    LIGHTCHAT = utils.Item(value="xf")  # LightChat
    GOFUNDME = utils.Item(value="bp")  # GoFundMe
    META = utils.Item(value="vy")  # Meta
    JAMESDELIVERY = utils.Item(value="ea")  # JamesDelivery
    SHELLBOX = utils.Item(value="vg")  # ShellBox
    REDBOOK = utils.Item(value="qf")  # RedBook
    TRIP = utils.Item(value="nq")  # Trip
    BIP = utils.Item(value="ww")  # BIP
    WHOOSH = utils.Item(value="qj")  # Whoosh
    KAZANEXPRESS = utils.Item(value="ol")  # KazanExpress
    AKULAKU = utils.Item(value="tm")  # Akulaku
    KEYPAY = utils.Item(value="ra")  # KeyPay
    BETFAIR = utils.Item(value="vd")  # Betfair
    GOJEK = utils.Item(value="ni")  # Gojek
    FASTMAIL = utils.Item(value="mr")  # Fastmail
    ALIEXPRESS = utils.Item(value="hx")  # AliExpress
    METRO = utils.Item(value="bv")  # Metro
    HANDYPICK = utils.Item(value="sj")  # HandyPick
    CHAINGEFINANCE = utils.Item(value="td")  # ChaingeFinance
    IWPLAY = utils.Item(value="dm")  # Iwplay
    GROUPME = utils.Item(value="xs")  # GroupMe
    NIMOTV = utils.Item(value="kz")  # NimoTV
    STRIPE = utils.Item(value="nu")  # Stripe
    EYECON = utils.Item(value="kr")  # Eyecon
    LIDL = utils.Item(value="pz")  # Lidl
    TWITCH = utils.Item(value="hb")  # Twitch
    GALAXYCHAT = utils.Item(value="xe")  # GalaxyChat
    ITI = utils.Item(value="ad")  # Iti
    SETEL = utils.Item(value="zg")  # Setel
    REVOLUT = utils.Item(value="ij")  # Revolut
    HERMES = utils.Item(value="en")  # Hermes
    KAGGLE = utils.Item(value="zo")  # Kaggle
    HEYBOX = utils.Item(value="vx")  # HeyBox
    BAND = utils.Item(value="hl")  # Band
    POTATO = utils.Item(value="lq")  # Potato
    ROPOSO = utils.Item(value="ga")  # Roposo
    WISE = utils.Item(value="bo")  # Wise
    KFC = utils.Item(value="fz")  # KFC
    OKCUPID = utils.Item(value="vm")  # OkCupid
    POCKET52 = utils.Item(value="ch")  # Pocket52
    PAYZAPP = utils.Item(value="yp")  # Payzapp
    AGRIDEVELOP = utils.Item(value="cs")  # AgriDevelop
    COURSEHERO = utils.Item(value="yg")  # CourseHero
    SANTANDER = utils.Item(value="lj")  # Santander
    POSHMARK = utils.Item(value="oz")  # Poshmark
    TANTAN = utils.Item(value="wh")  # TanTan
    IZI = utils.Item(value="wt")  # IZI
    OKKO = utils.Item(value="og")  # Okko
    MPL = utils.Item(value="xq")  # MPL
    OVO = utils.Item(value="xh")  # OVO
    VINTED = utils.Item(value="kc")  # Vinted
    SIZEER = utils.Item(value="eo")  # Sizeer
    NOON = utils.Item(value="tf")  # Noon
    WINZO = utils.Item(value="lv")  # WinZO
    ZOMATO = utils.Item(value="dy")  # Zomato
    DEWUPOISON = utils.Item(value="lx")  # DewuPoison
    GIFTCLOUD = utils.Item(value="nn")  # Giftcloud
    BILIBILI = utils.Item(value="zs")  # Bilibili
    VIVO = utils.Item(value="kx")  # Vivo
    TWILIO = utils.Item(value="ee")  # Twilio
    MR_GREEN = utils.Item(value="tp")  # Mr Green
    ROYALWIN = utils.Item(value="ku")  # RoyalWin
